Updated ec2.py to fix datetime is not JSON serializable
Updated Pull Request #20163 to fix contrib/inventory/ec2.py errors when working with RDS Aurora Mysql clusters that have three (as of 20180201) datetime attributes that were causing errors like:

TypeError: datetime.datetime(20167 1, 10, 21, 46, 24, 862000) is not JSON serializable

The current attributes that generate such error are:
- EarliestRestorableTime
- LatestRestorableTime
- ClusterCreateTime

Current version only filters out the first two, the third one makes the script die.

This updated patch is totally based on the work of @patrice and just updated to apply cleanly with current devel branch, it doesn't filter out the datetime attributes and correctly converts them.